// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Utilis
{
	public class UtilisTools
	{
		public static bool debugLoggingEnabled = true;

		public static void Log (object caller, string line)
		{
			if (debugLoggingEnabled)
				Debug.Log ("<color=yellow>[UTILIS]</color>["+caller.GetType ().Name + "]: " + line);
		}

		public static void LogError (object caller, string line, params object[] list)
		{
			Debug.LogError ("<color=red>[UTILIS]</color>["+caller.GetType ().Name + "]: " + line);
		}

	}
}

