//
//  UtilisLight.cs
//
//  Author:Bonus Eventus
//
//  Contact: fortuneetbono@gmail.com
//
//  Copyright (c) 2018 Bonus Eventus
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
namespace Utilis
{
	public class UtilisLight
	{
		public UtilisLight ()
		{}
		public UtilisLight (Light light)
		{
			_light = light;
			_orgIntensity = light.intensity;
			_orgRange = light.range;
			_orgSpotAngle = light.spotAngle;
		}
		private Light _light;

		private float _orgIntensity;

		private float _orgRange;

		private float _orgSpotAngle;

		public Light Light
		{
			get {return _light;}
		}

		public float orgIntensity
		{
			get {return _orgIntensity;}
		}

		public float orgRange
		{
			get {return _orgRange;}
		}

		public float orgSpotAngle
		{
			get {return _orgSpotAngle;}
		}

		public void SetLight(Light light)
		{
			_light = light;
			_orgIntensity = light.intensity;
			_orgRange = light.range;
			_orgSpotAngle = light.spotAngle;
		}

		public void SetIntensity(float intensity)
		{
			_light.intensity = intensity;
		}

		public void SetRange(float range)
		{
			_light.range = range;
		}

		public void SetColor(Color color)
		{
			_light.color = color;
		}

		public void Enable()
		{
			_light.enabled = true;
		}

		public void Disable()
		{
			_light.enabled = false;
		}

		public void SetSpotAngle(float spotAngle)
		{
			_light.spotAngle = spotAngle;
		}
	}
}

